Week3_Django/lecture3/hi/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path("brain",views.brain, name="brain"),
    path("david",views.david, name="david"),
    path("<str:name>", views.greet, name="greet" )
]

Week3_Django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hi/', include("hi.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

Week3_Django/lecture3/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"

urlpatterns = [
    path("", views.index, name="index")
]

Week3_Django/lecture3/tasks/urls.py
from django.urls import path
from . import views


app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

Week3_Django/lecture3/hi/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "hi/index.html")

def brain(request):
    return HttpResponse("Hey brain")

def david(request):
    return HttpResponse("Hey david")

def greet(request, name):
    return render(request, "hi/greet.html",{
        "name": name.capitalize()
    })

Week3_Django/lecture3/newyear/views.py
from django.shortcuts import render

# Create your views here.

from datetime import datetime



def index(request):
    now = datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

Week3_Django/lecture3/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse 
# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

tasks = ["foo", "bar", "baz"]

def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add/html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

Week3_Django/lecture3/hi/templates/hi/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hey</title>
</head>
<body>
    <h1>Hey, {{ name }}</h1>
</body>
</html>

Week3_Django/lecture3/hi/templates/hi/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hey</title>
</head>
<body>
    <h1>Hey, World!</h1>
</body>
</html>

Week3_Django/lecture3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>newyear</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

Week3_Django/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Tasks</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <input type="submit">
    </form>
    <br>

    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

Week3_Django/lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'tasks:add' %}">Add a new Task</a>
{% endblock %}

Week3_Django/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>